name: CI

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-update:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout kode dari repositori
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # 2. Setup lingkungan Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Ganti dengan versi Node.js proyek Anda

      # 3. Cache dependensi npm untuk mempercepat instalasi
      - name: Cache npm dependencies
        uses: actions/cache@v4
        id: npm-cache # Memberi id pada step cache
        with:
          path: ~/.npm # Path direktori cache npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4. Install dependensi proyek
      - name: Install Dependencies
        run: npm ci # 'ci' lebih cepat dan andal untuk CI/CD daripada 'install'
      - name: Sync to Google Drive
        uses: guillep2k/github-to-drive@latest
        with:
          source: './' # Direktori sumber (root repositori)
          destination: 'master' # Nama subfolder di dalam folder Drive Anda
          delete: 'true' # Hapus file lama di Drive yang tidak ada lagi di repo
        env:
          GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
          GDRIVE_FOLDERID: ${{ vars.GDRIVE_FOLDERID }}
